# Generated by Django 5.1.1 on 2024-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_and_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.TextField(default='New Notification'),
        ),
    ]
