# Generated by Django 5.1.1 on 2024-09-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
