# Generated by Django 5.1.1 on 2024-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
