# Generated by Django 5.1.1 on 2024-09-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_survey_reward_task_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='upload_complete',
            field=models.BooleanField(default=False),
        ),
    ]
