# Generated by Django 5.1.1 on 2024-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_withdrawrequest_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submit_type',
            field=models.CharField(choices=[('image', 'Image'), ('code', 'Code')], default='image', max_length=50),
        ),
    ]
