# Generated by Django 5.1.1 on 2024-09-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tasksubmit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='tasksubmit',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tasksubmit',
            name='image',
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='proof_of_work',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='points',
            field=models.DecimalField(decimal_places=4, default=1000.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
    ]
