# Generated by Django 5.1.1 on 2024-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_announcement_remove_tasksubmit_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawrequest',
            old_name='account_number',
            new_name='confirmed_account',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='bank_description',
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='wallet_address',
            field=models.TextField(default='falsw', help_text='USDT TRC 20 WALLET ADDRESS'),
            preserve_default=False,
        ),
    ]
